version: "3.9"

services:
  database:
    image: postgres:17-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: roadmap
      POSTGRES_PASSWORD: aiRmap123
      POSTGRES_DB: ai_roadmap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roadmap -d ai_roadmap"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    env_file:
     - ./server/.env
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - app-network

volumes:
  postgres_data:    

networks:
  app-network: